# -------------------------------------------------------
# Sobrio Light Theme
# Author: Elves Sousa <contato@elvessousa.com.br>
# -------------------------------------------------------

# Colors
"attribute" = { fg = "yellow", modifiers = ["italic"] }
"comment" = { fg = "gray", modifiers = ["italic"] }
"constant" = { fg = "purple" }
"constructor" = { fg = "cyan", modifiers = ["bold"] }
"error" = "red"
"field" = { modifiers = ["italic"] }
"function" = { fg = "white", modifiers = ["bold"] }
"hint" = "cyan"
"info" = "purple"
"keyword" = { fg = "red", modifiers = ["italic"] }
"namespace" = "yellow"
"numeric" = "purple"
"operator" = "red"
"punctuation" = "light-gray"
"special" = { fg = "yellow" }
"string" = "blue"
"tag" = { fg = "yellow", modifiers = ["bold"] }
"type" = { fg = "silver", modifiers = ["italic"] }
"variable" = "light"
"warning" = "yellow"

# UI
"ui.background" = { bg = "dark", fg = "splits" }
"ui.bufferline.active" = { fg = "yellow", bg = "dark", modifiers = ["bold"] }
"ui.bufferline" = { fg = "number", bg = "black" }
"ui.cursor" = { bg = "silver" }
"ui.cursorline" = { bg = "selection-bg" }
"ui.cursor.match" = { fg = "white", modifiers = ["bold"] }
"ui.help" = { bg = "dark", fg = "gray" }
"ui.linenr" = { fg = "number", modifiers = ["dim"] }
"ui.linenr.selected" = { fg = "silver" }
"ui.menu" = { fg = "silver", bg = "bg" }
"ui.menu.scroll" = { fg = "silver", bg = "gray" }
"ui.menu.selected" = { fg = "white", bg = "splits" }
"ui.popup" = { bg = "dark", fg = "splits" }
"ui.selection" = { fg ="brown", bg = "selection-bg" }
"ui.statusline" = { bg = "bg", fg = "white" }
"ui.statusline.insert" = { fg = "black", bg = "red", modifiers = ["bold"] }
"ui.statusline.normal" = { fg = "black", bg = "yellow", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "blue", modifiers = ["bold"] }
"ui.text.focus" = { fg = "white", bg = "hover" }
"ui.text" = "silver"
"ui.virtual.indent-guide" = "selection-bg"
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "selection-bg" }
"ui.virtual.wrap" = { fg = "fold" }
"ui.window" = { bg = "gray", fg = "gray" }

# Specific
"comment.documentation" = { fg = "light-gray", modifiers = ["italic"] }
"diagnostic.error" = { fg = "white", underline = { color = "red", style = "curl"} }
"diagnostic.hint" = { modifiers = ["underlined"] }
"diagnostic.info" = { fg = "gray", modifiers = ["dim"] }
"diagnostic.warning" = { fg = "yellow", modifiers = ["dim", "slow_blink"] }
"diff.delta" = "yellow"
"diff.minus" = "red"
"diff.plus" = "green"
"function.builtin" = { fg = "yellow", modifiers = ["bold"] }
"function.macro" = { fg = "yellow", modifiers = ["bold"] }
"keyword.control.import" = { fg = "red", modifiers = ["bold"] } 
"keyword.directive" = "yellow" 
"keyword.operator" = "red"
"keyword.storage" = { fg = "cyan", modifiers = ["italic"] } 
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "red", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { modifiers = ["italic"] }
"markup.link.text" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = { fg = "blue" }
"markup.raw" = { fg = "blue" }
"punctuation.delimiter" = "light-gray"
"string.special.path" = "cyan"
"string.special.symbol" = "yellow"
"string.special.url" = "cyan"
"type.builtin" = { fg = "silver", modifiers = ["italic"] }
"variable.builtin" = { fg = "silver", modifiers = ["italic"] }
"variable.other.member" = { fg = "white", modifiers = ["italic"] }
"variable.parameter" = { fg = "yellow" }


[palette]
black = "#ffffff"
blue = "#6787af"
brown = "#928374"
cyan = "#5fafaf"
dark = "#eeeeee"
gray = "#5f5f5f"
green = "#2cdce7"
light = "#121212"
light-gray = "#3a3b3f"
magenta = "#fd6389"
purple = "#9787af"
red = "#dd4c4f"
silver = "#5f5f5f"
white = "#000000"
yellow = "#af875f"

bg = "#f8f8f8"
fold = "#eeeeee"
hover = "#ffffff"
menu = "#efefef"
number = "#cccccc"
selection-bg = "#dddddd"
splits = "#cccccc"
visual = "#dddddd"
